#define F_CPU 16000000UL
#include <avr/io.h>
#include "drivers/spi.h"
#include "drivers/ili9341.h"
#include "inputs/button.h"
#include "font/font.h"
#include "buzzer/buzzer.h"

static const BuzzerNote tetris[] = {
    // A section
    {NOTE_E5, DUR_QUARTER}, {NOTE_B4, DUR_EIGHTH},  {NOTE_C5, DUR_EIGHTH},
    {NOTE_D5, DUR_QUARTER}, {NOTE_C5, DUR_EIGHTH},  {NOTE_B4, DUR_EIGHTH},
    {NOTE_A4, DUR_QUARTER}, {NOTE_A4, DUR_EIGHTH},  {NOTE_C5, DUR_EIGHTH},
    {NOTE_E5, DUR_QUARTER}, {NOTE_D5, DUR_EIGHTH},  {NOTE_C5, DUR_EIGHTH},
    {NOTE_B4, DUR_DOT_QUARTER}, {NOTE_C5, DUR_EIGHTH}, {NOTE_D5, DUR_QUARTER},
    {NOTE_E5, DUR_QUARTER}, {NOTE_C5, DUR_QUARTER}, {NOTE_A4, DUR_QUARTER},
    {NOTE_A4, DUR_HALF},    {NOTE_REST, DUR_QUARTER},

    {NOTE_D5, DUR_QUARTER}, {NOTE_F5, DUR_EIGHTH},  {NOTE_A5, DUR_QUARTER},
    {NOTE_G5, DUR_EIGHTH},  {NOTE_F5, DUR_EIGHTH},  {NOTE_E5, DUR_DOT_QUARTER},
    {NOTE_C5, DUR_EIGHTH},  {NOTE_E5, DUR_QUARTER},  {NOTE_D5, DUR_EIGHTH},
    {NOTE_C5, DUR_EIGHTH},  {NOTE_B4, DUR_DOT_QUARTER}, {NOTE_C5, DUR_EIGHTH},
    {NOTE_D5, DUR_QUARTER}, {NOTE_E5, DUR_QUARTER},
    {NOTE_C5, DUR_QUARTER}, {NOTE_A4, DUR_QUARTER},
    {NOTE_A4, DUR_HALF},    {NOTE_REST, DUR_QUARTER},

    // A section repeat
    {NOTE_E5, DUR_QUARTER}, {NOTE_B4, DUR_EIGHTH},  {NOTE_C5, DUR_EIGHTH},
    {NOTE_D5, DUR_QUARTER}, {NOTE_C5, DUR_EIGHTH},  {NOTE_B4, DUR_EIGHTH},
    {NOTE_A4, DUR_QUARTER}, {NOTE_A4, DUR_EIGHTH},  {NOTE_C5, DUR_EIGHTH},
    {NOTE_E5, DUR_QUARTER}, {NOTE_D5, DUR_EIGHTH},  {NOTE_C5, DUR_EIGHTH},
    {NOTE_B4, DUR_DOT_QUARTER}, {NOTE_C5, DUR_EIGHTH}, {NOTE_D5, DUR_QUARTER},
    {NOTE_E5, DUR_QUARTER}, {NOTE_C5, DUR_QUARTER}, {NOTE_A4, DUR_QUARTER},
    {NOTE_A4, DUR_HALF},    {NOTE_REST, DUR_QUARTER},

    {NOTE_D5, DUR_QUARTER}, {NOTE_F5, DUR_EIGHTH},  {NOTE_A5, DUR_QUARTER},
    {NOTE_G5, DUR_EIGHTH},  {NOTE_F5, DUR_EIGHTH},  {NOTE_E5, DUR_DOT_QUARTER},
    {NOTE_C5, DUR_EIGHTH},  {NOTE_E5, DUR_QUARTER},  {NOTE_D5, DUR_EIGHTH},
    {NOTE_C5, DUR_EIGHTH},  {NOTE_B4, DUR_DOT_QUARTER}, {NOTE_C5, DUR_EIGHTH},
    {NOTE_D5, DUR_QUARTER}, {NOTE_E5, DUR_QUARTER},
    {NOTE_C5, DUR_QUARTER}, {NOTE_A4, DUR_QUARTER},
    {NOTE_A4, DUR_HALF},    {NOTE_REST, DUR_QUARTER},

    // B section
    {NOTE_E5, DUR_HALF},    {NOTE_C5, DUR_HALF},
    {NOTE_D5, DUR_HALF},    {NOTE_B4, DUR_HALF},
    {NOTE_C5, DUR_HALF},    {NOTE_A4, DUR_HALF},
    {NOTE_GS4, DUR_HALF},   {NOTE_B4, DUR_QUARTER}, {NOTE_REST, DUR_QUARTER},

    {NOTE_E5, DUR_HALF},    {NOTE_C5, DUR_HALF},
    {NOTE_D5, DUR_HALF},    {NOTE_B4, DUR_HALF},
    {NOTE_C5, DUR_QUARTER}, {NOTE_E5, DUR_QUARTER}, {NOTE_A5, DUR_HALF},
    {NOTE_A5, DUR_HALF},    {NOTE_REST, DUR_QUARTER},

    // A section final
    {NOTE_E5, DUR_QUARTER}, {NOTE_B4, DUR_EIGHTH},  {NOTE_C5, DUR_EIGHTH},
    {NOTE_D5, DUR_QUARTER}, {NOTE_C5, DUR_EIGHTH},  {NOTE_B4, DUR_EIGHTH},
    {NOTE_A4, DUR_QUARTER}, {NOTE_A4, DUR_EIGHTH},  {NOTE_C5, DUR_EIGHTH},
    {NOTE_E5, DUR_QUARTER}, {NOTE_D5, DUR_EIGHTH},  {NOTE_C5, DUR_EIGHTH},
    {NOTE_B4, DUR_DOT_QUARTER}, {NOTE_C5, DUR_EIGHTH}, {NOTE_D5, DUR_QUARTER},
    {NOTE_E5, DUR_QUARTER}, {NOTE_C5, DUR_QUARTER}, {NOTE_A4, DUR_QUARTER},
    {NOTE_A4, DUR_HALF},    {NOTE_REST, DUR_QUARTER},

    {NOTE_D5, DUR_QUARTER}, {NOTE_F5, DUR_EIGHTH},  {NOTE_A5, DUR_QUARTER},
    {NOTE_G5, DUR_EIGHTH},  {NOTE_F5, DUR_EIGHTH},  {NOTE_E5, DUR_DOT_QUARTER},
    {NOTE_C5, DUR_EIGHTH},  {NOTE_E5, DUR_QUARTER},  {NOTE_D5, DUR_EIGHTH},
    {NOTE_C5, DUR_EIGHTH},  {NOTE_B4, DUR_DOT_QUARTER}, {NOTE_C5, DUR_EIGHTH},
    {NOTE_D5, DUR_QUARTER}, {NOTE_E5, DUR_QUARTER},
    {NOTE_C5, DUR_QUARTER}, {NOTE_A4, DUR_QUARTER},
    {NOTE_A4, DUR_HALF},
};

#define tetris_length (sizeof(tetris) / sizeof(tetris[0]))  //anzahl der notes automatisch rechnen

int main(void)
{
   
   spi_init();
   ili9341_init();
   button_init();
   buzzer_init();
   
   while (1) 
   {

    buzzer_play(tetris, tetris_length);

   }
   return 0;
}